server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: device-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/devices/**
        - id: data-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/data/**
        - id: ai-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/ai/**
        - id: vision-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/vision/**

